In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys, os
sys.path.append('..')

import numpy as np
import librosa as lr
import torch
import IPython.display as ipd

from datasets.nsynth_datamodule import NsynthDataModule

In [5]:
configs = {
    'dataset_path': '/data/riccardo_datasets',
    'feature': 'spec',
    'feature_params': {
        'win_length': 256,
        'hop_length': 64
    },
    'n_fft': 256,
    'ds_kwargs': {
        'pitches': [60, 61, 62],
        'duration': 2
    }
}

In [6]:
dm = NsynthDataModule(configs, num_workers=0, batch_size=4)
dm.setup('test')
dl = dm.test_dataloader()

{'win_length': 256, 'hop_length': 64}
/data/riccardo_datasets/nsynth-test/examples.json


/home/rmicci18/miniconda3/envs/sound_morph/lib/python3.8/site-packages/torch/functional.py:515: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607369981906/work/aten/src/ATen/native/SpectralOps.cpp:590.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore


In [7]:
a = next(iter(dl))
a[0].shape

torch.Size([4, 129, 501, 2])

In [9]:
a[1]

{'qualities': [tensor([0, 0, 0, 0]),
  tensor([1, 0, 0, 1]),
  tensor([0, 0, 0, 0]),
  tensor([0, 0, 0, 0]),
  tensor([0, 0, 0, 0]),
  tensor([0, 0, 0, 0]),
  tensor([0, 0, 0, 0]),
  tensor([0, 0, 0, 0]),
  tensor([0, 1, 1, 0]),
  tensor([0, 0, 0, 0])],
 'pitch': tensor([60, 61, 62, 61]),
 'note': tensor([248525,  74272,  27009, 259543]),
 'instrument_source_str': ['electronic', 'acoustic', 'acoustic', 'electronic'],
 'velocity': tensor([127,  75, 127, 100]),
 'instrument_str': ['organ_electronic_001',
  'guitar_acoustic_015',
  'brass_acoustic_015',
  'organ_electronic_057'],
 'instrument': tensor([  8, 316, 121, 701]),
 'sample_rate': tensor([16000, 16000, 16000, 16000]),
 'instrument_source': tensor([1, 0, 0, 1]),
 'note_str': ['organ_electronic_001-060-127',
  'guitar_acoustic_015-061-075',
  'brass_acoustic_015-062-127',
  'organ_electronic_057-061-100'],
 'instrument_family': tensor([6, 3, 1, 6]),
 'instrument_family_str': ['organ', 'guitar', 'brass', 'organ']}

In [8]:
aa = torch.istft(a[0], n_fft=256, win_length=256, hop_length=64)
aa.shape

/home/rmicci18/miniconda3/envs/sound_morph/lib/python3.8/site-packages/torch/functional.py:586: UserWarning: The function torch.irfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.ifft or torch.fft.irfft. (Triggered internally at  /opt/conda/conda-bld/pytorch_1607369981906/work/aten/src/ATen/native/SpectralOps.cpp:602.)
  return _VF.istft(input, n_fft, hop_length, win_length, window, center,  # type: ignore


torch.Size([4, 32000])